env:
  node: true
  jest: true
  es6: true
parserOptions:
  ecmaVersion: 8
extends:
  - google
rules:
  strict:
    - error
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
  no-tabs:
    -	off